/* tslint:disable */
/* eslint-disable */
/**
 * Simple Bank API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dotu30257@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbUser } from './PbUser';
import {
    PbUserFromJSON,
    PbUserFromJSONTyped,
    PbUserToJSON,
} from './PbUser';

/**
 * 
 * @export
 * @interface PbCreateUserResponse
 */
export interface PbCreateUserResponse {
    /**
     * 
     * @type {PbUser}
     * @memberof PbCreateUserResponse
     */
    user?: PbUser;
}

/**
 * Check if a given object implements the PbCreateUserResponse interface.
 */
export function instanceOfPbCreateUserResponse(value: object): value is PbCreateUserResponse {
    return true;
}

export function PbCreateUserResponseFromJSON(json: any): PbCreateUserResponse {
    return PbCreateUserResponseFromJSONTyped(json, false);
}

export function PbCreateUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbCreateUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : PbUserFromJSON(json['user']),
    };
}

export function PbCreateUserResponseToJSON(value?: PbCreateUserResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': PbUserToJSON(value['user']),
    };
}

