/* tslint:disable */
/* eslint-disable */
/**
 * Simple Bank API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dotu30257@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbUser } from './PbUser';
import {
    PbUserFromJSON,
    PbUserFromJSONTyped,
    PbUserToJSON,
} from './PbUser';

/**
 * 
 * @export
 * @interface PbLoginUserResponse
 */
export interface PbLoginUserResponse {
    /**
     * 
     * @type {string}
     * @memberof PbLoginUserResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {Date}
     * @memberof PbLoginUserResponse
     */
    accessTokenExpriedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PbLoginUserResponse
     */
    refreshToken?: string;
    /**
     * 
     * @type {Date}
     * @memberof PbLoginUserResponse
     */
    refreshTokenExpriedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PbLoginUserResponse
     */
    sessionId?: string;
    /**
     * 
     * @type {PbUser}
     * @memberof PbLoginUserResponse
     */
    user?: PbUser;
}

/**
 * Check if a given object implements the PbLoginUserResponse interface.
 */
export function instanceOfPbLoginUserResponse(value: object): value is PbLoginUserResponse {
    return true;
}

export function PbLoginUserResponseFromJSON(json: any): PbLoginUserResponse {
    return PbLoginUserResponseFromJSONTyped(json, false);
}

export function PbLoginUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbLoginUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'accessTokenExpriedAt': json['accessTokenExpriedAt'] == null ? undefined : (new Date(json['accessTokenExpriedAt'])),
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'refreshTokenExpriedAt': json['refreshTokenExpriedAt'] == null ? undefined : (new Date(json['refreshTokenExpriedAt'])),
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'user': json['user'] == null ? undefined : PbUserFromJSON(json['user']),
    };
}

export function PbLoginUserResponseToJSON(value?: PbLoginUserResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accessToken': value['accessToken'],
        'accessTokenExpriedAt': value['accessTokenExpriedAt'] == null ? undefined : ((value['accessTokenExpriedAt']).toISOString()),
        'refreshToken': value['refreshToken'],
        'refreshTokenExpriedAt': value['refreshTokenExpriedAt'] == null ? undefined : ((value['refreshTokenExpriedAt']).toISOString()),
        'sessionId': value['sessionId'],
        'user': PbUserToJSON(value['user']),
    };
}

