/* tslint:disable */
/* eslint-disable */
/**
 * Simple Bank API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dotu30257@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PbLoginUserRequest
 */
export interface PbLoginUserRequest {
    /**
     * 
     * @type {string}
     * @memberof PbLoginUserRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof PbLoginUserRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the PbLoginUserRequest interface.
 */
export function instanceOfPbLoginUserRequest(value: object): value is PbLoginUserRequest {
    return true;
}

export function PbLoginUserRequestFromJSON(json: any): PbLoginUserRequest {
    return PbLoginUserRequestFromJSONTyped(json, false);
}

export function PbLoginUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbLoginUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function PbLoginUserRequestToJSON(value?: PbLoginUserRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

