/* tslint:disable */
/* eslint-disable */
/**
 * Simple Bank API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dotu30257@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PbUpdateUserRequest
 */
export interface PbUpdateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof PbUpdateUserRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof PbUpdateUserRequest
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof PbUpdateUserRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PbUpdateUserRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the PbUpdateUserRequest interface.
 */
export function instanceOfPbUpdateUserRequest(value: object): value is PbUpdateUserRequest {
    return true;
}

export function PbUpdateUserRequestFromJSON(json: any): PbUpdateUserRequest {
    return PbUpdateUserRequestFromJSONTyped(json, false);
}

export function PbUpdateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbUpdateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function PbUpdateUserRequestToJSON(value?: PbUpdateUserRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
        'fullName': value['fullName'],
        'email': value['email'],
        'password': value['password'],
    };
}

