/* tslint:disable */
/* eslint-disable */
/**
 * Simple Bank API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dotu30257@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PbUser } from './PbUser';
import {
    PbUserFromJSON,
    PbUserFromJSONTyped,
    PbUserToJSON,
} from './PbUser';

/**
 * 
 * @export
 * @interface PbUpdateUserResponse
 */
export interface PbUpdateUserResponse {
    /**
     * 
     * @type {PbUser}
     * @memberof PbUpdateUserResponse
     */
    user?: PbUser;
}

/**
 * Check if a given object implements the PbUpdateUserResponse interface.
 */
export function instanceOfPbUpdateUserResponse(value: object): value is PbUpdateUserResponse {
    return true;
}

export function PbUpdateUserResponseFromJSON(json: any): PbUpdateUserResponse {
    return PbUpdateUserResponseFromJSONTyped(json, false);
}

export function PbUpdateUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbUpdateUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : PbUserFromJSON(json['user']),
    };
}

export function PbUpdateUserResponseToJSON(value?: PbUpdateUserResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': PbUserToJSON(value['user']),
    };
}

