/* tslint:disable */
/* eslint-disable */
/**
 * Simple Bank API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dotu30257@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PbUser
 */
export interface PbUser {
    /**
     * 
     * @type {string}
     * @memberof PbUser
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof PbUser
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof PbUser
     */
    email?: string;
    /**
     * 
     * @type {Date}
     * @memberof PbUser
     */
    passwordChangedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PbUser
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the PbUser interface.
 */
export function instanceOfPbUser(value: object): value is PbUser {
    return true;
}

export function PbUserFromJSON(json: any): PbUser {
    return PbUserFromJSONTyped(json, false);
}

export function PbUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbUser {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'email': json['email'] == null ? undefined : json['email'],
        'passwordChangedAt': json['passwordChangedAt'] == null ? undefined : (new Date(json['passwordChangedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function PbUserToJSON(value?: PbUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
        'fullName': value['fullName'],
        'email': value['email'],
        'passwordChangedAt': value['passwordChangedAt'] == null ? undefined : ((value['passwordChangedAt']).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

