/* tslint:disable */
/* eslint-disable */
/**
 * Simple Bank API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dotu30257@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PbVerifyEmailResponse
 */
export interface PbVerifyEmailResponse {
    /**
     * 
     * @type {boolean}
     * @memberof PbVerifyEmailResponse
     */
    isVerified?: boolean;
}

/**
 * Check if a given object implements the PbVerifyEmailResponse interface.
 */
export function instanceOfPbVerifyEmailResponse(value: object): value is PbVerifyEmailResponse {
    return true;
}

export function PbVerifyEmailResponseFromJSON(json: any): PbVerifyEmailResponse {
    return PbVerifyEmailResponseFromJSONTyped(json, false);
}

export function PbVerifyEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PbVerifyEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isVerified': json['isVerified'] == null ? undefined : json['isVerified'],
    };
}

export function PbVerifyEmailResponseToJSON(value?: PbVerifyEmailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isVerified': value['isVerified'],
    };
}

