# name: Push Docker Image to GCP

# on:
#   push:
#     branches:
#       - main

# jobs:
#   push-to-gcp:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Configure Docker to use GCP credentials
#       run: |
#         echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} | base64 -d > /tmp/gcp-sa-key.json
#         docker login -u _json_key --password-stdin gcr.io < /tmp/gcp-sa-key.json

#     - name: Build and push Docker image to GCP
#       run: |
#         docker buildx build --platform linux/amd64,linux/arm64 -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.repository }}:${{ github.sha }} .
#         docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.repository }}:${{ github.sha }}
